// Generated by CoffeeScript 1.9.2
(function() {
  var CoffeeScriptInstrumenter;

  CoffeeScriptInstrumenter = require("./coffeescript_instrumenter").CoffeeScriptInstrumenter;

  exports.CoffeeScriptInstrumenter = CoffeeScriptInstrumenter;

}).call(this);
