// Generated by CoffeeScript 1.9.3
(function() {
  var instrumentCoffee;

  instrumentCoffee = require("./coffeescript_instrumenter").instrumentCoffee;

  exports.instrumentCoffee = instrumentCoffee;

}).call(this);
