// Generated by CoffeeScript 1.9.3
(function() {
  var Scope;

  Scope = (function() {
    function Scope(parent) {
      this.parent = parent;
      this.vars = [];
    }

    Scope.prototype.add = function(variable) {
      if (this.vars.indexOf(variable) === -1) {
        return this.vars.push(variable);
      }
    };

    Scope.prototype.toCode = function() {
      var code, curScope, i, ident, len, ref;
      curScope = this;
      code = "{ ";
      while (curScope) {
        ref = curScope.vars;
        for (i = 0, len = ref.length; i < len; i++) {
          ident = ref[i];
          code += ident + ": " + ident + ", ";
        }
        curScope = curScope.parent;
      }
      code += "}";
      return code;
    };

    return Scope;

  })();

  exports.Scope = Scope;

}).call(this);
