// Generated by CoffeeScript 1.9.3
(function() {
  var Scope;

  Scope = (function() {
    function Scope(parent) {
      this.parent = parent;
      this.vars = [];
    }

    Scope.prototype.add = function(variable, type) {
      if (this.vars.indexOf(variable) === -1) {
        return this.vars.push({
          name: variable,
          type: type
        });
      }
    };

    Scope.prototype.toCode = function() {
      var code, curScope, i, len, ref, variable;
      curScope = this;
      code = "[ ";
      while (curScope) {
        ref = curScope.vars;
        for (i = 0, len = ref.length; i < len; i++) {
          variable = ref[i];
          code += "{ name: '" + variable.name + "', value: " + variable.name + ", type: '" + variable.type + "' }, ";
        }
        curScope = curScope.parent;
      }
      code += "]";
      return code;
    };

    return Scope;

  })();

  exports.Scope = Scope;

}).call(this);
